# This docker-compose.yml file sets up a Docker network with two services: Postgres and PgAdmin.
# It configures necessary environment variables, volume mounting, and port mapping for both containers.


services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=p1user
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    
